version: '3.8'
services:
  sftp:
    image: atmoz/sftp
    ports:
      - "22:22"
    volumes:
      - sftp_data:/home/testuser/upload
    environment:
      SFTP_USERS: "testuser:password:1001"
volumes:
  sftp_data: